### ISSUE TITLE
mod文件编码

### ISSUE THREAD

**Issue by oweaF** [vvsolo/vvsolo.github.io#1]
版本：微云Everedit-min.210203.7z
系统：win10 20H2 UTF-8
mod文件`UTF-8`,`ASNI`,`GB2312`三种编码混杂着，程序用起来会乱码

**Comment by vvsolo** [comment]
抱歉，才看到。
Everedit 只是文本或代码编辑器，文本一般都是单一编码。
一些特殊文件不适合用此软件编辑。

不知道mod文件是何结构？

**Comment by oweaF** [comment]
我指的是`~/macro`文件夹下的批处理文件编码混杂
具体表现是批处理菜单文本乱码
估计是我设置了系统层面的UTF-8编码导致的
![image](https://user-images.githubusercontent.com/25154231/112983488-573f0c80-9190-11eb-858c-eed53941e8bb.png)

**Comment by vvsolo** [comment]
Everedit  脚本文件如果是UTF-8必须加BOM才能运行，如果是GBK也可以运行。
为减少文件大小，保存脚本时编码是混杂的。
你可以全部转换为UTF-8+格式，测试是否有乱码。

**Comment by oweaF** [comment]
把非UTF-8编码的文件转为UTF-8后，目前为止功能正常
