### ISSUE TITLE
遇到一些问题

### ISSUE THREAD

**Issue by loveqianool** [vvsolo/vvsolo.github.io#2]
```
　　我连忙摇头道：“苗人？不是的，是“斩虎刀”段天虎的暗器。”

　　待那丫鬟去了，又向另一名小丫鬟道：「叫些人去把后院的几间厢房收拾收
拾，快入秋的天了，夜里定要起凉，别忘了往被里加些棉。」

　　待那丫鬟去了，又向另一名小丫鬟道：「叫些人去把后院的几间厢房收拾
一回，快入秋的天了，夜里定要起凉，别忘了往被里加些棉。」
```
上面这第一段，因为没有先处理内部引号，整理排版后会出现  `」斩虎刀「`引号错误。
第二段那个拾在软件里面会被识别为标题，而番外开头又不能识别为标题，这个可以自定义吗？
第三段那个一回会自动替换成第一回，这个会修改原文语义的功能能给个选项关掉吗？

**Comment by vvsolo** [comment]
一、网页版无法解决引号嵌套的问题，要用软件；
二、分段后的文本不适用于整理过程，需要先反向整理成普通格式；
数字（包括某些大写）会被识别成标题在大纲显示，以便定位；
番外这种特殊的章节，需要后面有分隔符才能被识别，否则容易被错误转换；
三、同〔二〕

综上，排版前的整理需要恢复最初文本样式，即无缩进、无分段。

**Comment by vvsolo** [comment]
> 就是先点 特殊 再点 整理 然后再点 排版 对吧。

是的
