### ISSUE TITLE
240801 版本下载地址没有看到

### ISSUE THREAD

**Issue by lzw99733080** [vvsolo/vvsolo.github.io#5]
作者好，网站(https://vvsolo.github.io/)上有240801更新日志，但是下载地址里没有新版。

**Comment by vvsolo** [comment]
抱歉现在才回复你。
在线版本同步比较方便，日志是同步记录，因此会快些。
软件修改后要测试一段时间。

**Comment by lzw99733080** [comment]
好的，谢谢回复
